port 26379
protected-mode no
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor matrix-master sentinel-master 6379 1
sentinel down-after-milliseconds matrix-master 5000
sentinel failover-timeout matrix-master 10000
